language: generic

os:
  - linux
  - osx

osx_image: xcode9.3

env:
  - LLVM_VERSION=3.4 PYTHON_VERSION=2
  - LLVM_VERSION=3.5 PYTHON_VERSION=2
  - LLVM_VERSION=3.6 PYTHON_VERSION=2
  - LLVM_VERSION=3.7 PYTHON_VERSION=2
  - LLVM_VERSION=3.8 PYTHON_VERSION=2
  - LLVM_VERSION=3.9 PYTHON_VERSION=2
  - LLVM_VERSION=4.0 PYTHON_VERSION=2
  - LLVM_VERSION=5.0 PYTHON_VERSION=2
  - LLVM_VERSION=6.0 PYTHON_VERSION=2
  - LLVM_VERSION=7 PYTHON_VERSION=2
  - LLVM_VERSION=8 PYTHON_VERSION=2
  - LLVM_VERSION=3.4 PYTHON_VERSION=3
  - LLVM_VERSION=3.5 PYTHON_VERSION=3
  - LLVM_VERSION=3.6 PYTHON_VERSION=3
  - LLVM_VERSION=3.7 PYTHON_VERSION=3
  - LLVM_VERSION=3.8 PYTHON_VERSION=3
  - LLVM_VERSION=3.9 PYTHON_VERSION=3
  - LLVM_VERSION=4.0 PYTHON_VERSION=3
  - LLVM_VERSION=5.0 PYTHON_VERSION=3
  - LLVM_VERSION=6.0 PYTHON_VERSION=3
  - LLVM_VERSION=7 PYTHON_VERSION=3
  - LLVM_VERSION=8 PYTHON_VERSION=3

# Exclude LLVM versions not available on brew
matrix:
  exclude:
  - os: osx
    env: LLVM_VERSION=3.4 PYTHON_VERSION=2
  - os: osx
    env: LLVM_VERSION=3.5 PYTHON_VERSION=2
  - os: osx
    env: LLVM_VERSION=3.6 PYTHON_VERSION=2
  - os: osx
    env: LLVM_VERSION=3.7 PYTHON_VERSION=2
  - os: osx
    env: LLVM_VERSION=3.8 PYTHON_VERSION=2
  - os: osx
    env: LLVM_VERSION=3.4 PYTHON_VERSION=3
  - os: osx
    env: LLVM_VERSION=3.5 PYTHON_VERSION=3
  - os: osx
    env: LLVM_VERSION=3.6 PYTHON_VERSION=3
  - os: osx
    env: LLVM_VERSION=3.7 PYTHON_VERSION=3
  - os: osx
    env: LLVM_VERSION=3.8 PYTHON_VERSION=3

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.4 main"
        key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.5 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.6 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main"

before_install:
  - |
    if [[ "$PYTHON_VERSION" == "2" ]]; then
      export PYTHON=python
      export PIP=pip
    elif [[ "$PYTHON_VERSION" == "3" ]]; then
      export PYTHON=python3
      export PIP=pip3
    fi

    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update
      sudo -E apt-get -yq --no-install-suggests --no-install-recommends \
        --force-yes install -t llvm-toolchain-trusty-3.9 \
        $PYTHON $PYTHON-pip llvm-$LLVM_VERSION-dev
      export LLVM_CONFIG=llvm-config-$LLVM_VERSION
    fi

    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew unlink python
      LLVM_VERSION=${LLVM_VERSION/.0/}
      brew install -f -v python@$PYTHON_VERSION llvm@$LLVM_VERSION
      export PATH="/usr/local/opt/llvm@$LLVM_VERSION/bin:$PATH"
      export LLVM_CONFIG=$(which llvm-config || which llvm-config-$LLVM_VERSION)
      export DYLD_LIBRARY_PATH="$($LLVM_CONFIG --libdir)"
    fi

install:
  - $PIP install --user -e .

script:
  - $PYTHON setup.py test
