language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 2.7
    - os: linux
      dist: trusty
      sudo: required
      python: 3.6
    - os: osx
      osx_image: xcode9.3
      # python is not a supported language on travis osx: https://docs.travis-ci.com/user/multi-os/
      language: generic


addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.4 main"
        key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.5 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.6 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main"
    packages:
    - llvm-3.4-dev
    - llvm-3.5-dev
    - llvm-3.6-dev
    - llvm-3.7-dev
    - llvm-3.8-dev
    - llvm-4.0-dev
    - llvm-5.0-dev
    - llvm-6.0-dev

before_install:
  - export LLVMCPY_SRC=`pwd`
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install zlib && brew link --force zlib  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ${LLVMCPY_SRC}/.travis/install_llvm.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/llvm/bin:$PATH" ; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install -t llvm-toolchain-trusty-3.9 llvm-3.9-dev ; fi

# On travis, clang-3.5 in /usr/local includes an llvm-config that comes earlier
# in the path than the system llvm
env:
  - LLVM_CONFIG=/usr/bin/llvm-config-3.4
  - LLVM_CONFIG=/usr/bin/llvm-config-3.5
  - LLVM_CONFIG=/usr/bin/llvm-config-3.6
  - LLVM_CONFIG=/usr/bin/llvm-config-3.7
  - LLVM_CONFIG=/usr/bin/llvm-config-3.8
  - LLVM_CONFIG=/usr/bin/llvm-config-3.9
  - LLVM_CONFIG=/usr/bin/llvm-config-4.0
  - LLVM_CONFIG=/usr/bin/llvm-config-5.0
  - LLVM_CONFIG=/usr/bin/llvm-config-6.0

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install -e . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install --user -e . ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  python setup.py test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py test ; fi
